export interface Player {
  name: String,
  tLink: String,
  team: String,
  number: String,
  position: String,
  nationality: Array<String>,
  age: String,
  overallRating: number,
  marketValue: String,
  specialities: Array<String>,
  speed: number,
  finishing: number,
  tactics: number,
  passing: number,
  technics: number,
  reactions: number,
  defense: number,
  tacticsInDefense: number,
  physics: number,
  creativity: number,
  goalkeeping: {
    gKDiving: number,
    gKHandling: number,
    gKKicking: number,
    gKPositioning: number,
    gKReflexes: number,
  },
}
